In [1]:
import sys
sys.version

'3.8.10 (default, Apr 29 2022, 16:40:34) \n[Clang 13.0.0 (clang-1300.0.29.3)]'

In [2]:
import numpy as np

In [3]:
arr = np.array([2,3,4])
arr

array([2, 3, 4])

In [5]:
arange = np.arange(0, 11, 3)
arange

array([0, 3, 6, 9])

In [8]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
z1 = np.zeros((3,4))
z1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
o = np.ones(4)
o

array([1., 1., 1., 1.])

In [12]:
o1 = np.ones((4,3))
o1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ri = np.random.randint(1,10)
ri

2

In [25]:
rx = np.random.randint(1,10,3)
rx

array([8, 7, 8])

In [24]:
rr = np.random.randint(1,20, (3,4))
rr

array([[ 5, 16, 12, 18],
       [ 4, 19,  7, 15],
       [11, 17,  4,  8]])

In [30]:
ls = np.linspace(0,20,5)
ls

array([ 0.,  5., 10., 15., 20.])

In [33]:
lss = np.linspace(0,20,3)
lss

array([ 0., 10., 20.])

In [37]:
matr = np.linspace((1,30),(30,60),6)
matr

array([[ 1. , 30. ],
       [ 6.8, 36. ],
       [12.6, 42. ],
       [18.4, 48. ],
       [24.2, 54. ],
       [30. , 60. ]])

In [52]:
np.random.seed(10)

In [56]:
arr = np.random.randint(1,100,10)
arr

array([31, 31, 90, 13, 66, 32, 58, 37, 28, 19])

In [57]:
arr.max()

90

In [58]:
arr.min()

13

In [59]:
arr.mean()

40.5

In [60]:
arr.argmax()

2

In [61]:
arr.argmin()

3

In [62]:
arr.reshape(2,5)

array([[31, 31, 90, 13, 66],
       [32, 58, 37, 28, 19]])

In [68]:
mat = np.arange(100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [70]:
mat[4, 5]

45

In [71]:
mat[:, 6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [72]:
mat[7, :]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [75]:
mat[4:7, 4:7]

array([[44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

In [77]:
mat[2:6, 3:8]

array([[23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37],
       [43, 44, 45, 46, 47],
       [53, 54, 55, 56, 57]])

In [78]:
mat[6:9, 2:6]

array([[62, 63, 64, 65],
       [72, 73, 74, 75],
       [82, 83, 84, 85]])

## Exersise

In [79]:
import numpy as np
import pandas as pd

In [80]:
np.random.seed(101)

In [93]:
arr = np.random.randint(0,101, (100,5))
arr

array([[  6,  34,  65,  72,  76],
       [ 88,  37,  98,  57,  69],
       [ 51,  59,  18,  13,  53],
       [ 67,  80,  67,  23,  55],
       [ 86,  38,   8,  31,  46],
       [ 80,  42,   2,  87,  69],
       [ 51,  91,  46,  91,  55],
       [ 27,  15,   7,  97,   2],
       [ 33,  67,  51,  47,  49],
       [  3,  70,   4,  66,   5],
       [ 76,  51,  39,  42,   8],
       [  1,  20,  50,  17,  41],
       [ 14,  22,  98,   7,  64],
       [  6,  71,  76,  28,  66],
       [ 78,  61,  66,  24,  15],
       [ 53,  44,  49,  91,  24],
       [ 99,  28,  42,  86,  68],
       [ 72,  19,   2,  25,  31],
       [ 89,  23,  22,  22,  52],
       [ 80,  62,   7,  57,   7],
       [ 40,  82,  95,  70,  28],
       [ 78,   3,  68,  97,  78],
       [ 93,  81,  18,  78,  29],
       [ 92,  81,  20,  90,   4],
       [ 45,  76,  29,  84,  13],
       [ 42,  23,  38,  76,  16],
       [ 31,  91,  26,  10,  88],
       [ 36,  67,  30,   6,  56],
       [ 20,  92,  70,   2,  80],
       [ 19,  

In [94]:
df = pd.DataFrame(arr, columns=['f1','f2','f3','f4','f5'])
df

f1   f2  f3  f4  f5
0    6   34  65  72  76
1   88   37  98  57  69
2   51   59  18  13  53
3   67   80  67  23  55
4   86   38   8  31  46
..  ..  ...  ..  ..  ..
95  60   72   9  95  96
96  46   59  51  47   4
97  59   36  34  98  81
98   8  100  95  60  46
99  19   13  35  14   6

[100 rows x 5 columns]

In [95]:
df1 = pd.DataFrame(np.random.randint(0,100, (50,4)), columns=['A','B','C','D'])
df1

A   B   C   D
0   24  31   9  31
1   12  48  75  25
2   85  62  21  77
3   68  19  66  70
4   73  49  27  35
5   33  42  33  93
6   39  64   1  58
7   17  59  71   1
8   23  80  26  37
9   34   3  77  20
10   0  62  29  47
11  48  89  49  17
12  86  47  49  63
13  31  35  56  83
14  71  72  11  26
15   2  16   0  50
16   8  79   1   1
17  42  28  90  35
18  85  23  64  20
19  21  43  37  89
20  32  66   2   2
21   0  90  90  56
22  70  53  38  89
23  30  20  20  46
24  20   9   7  66
25  17  65  69   7
26  45  18  73  29
27  69  91  52  91
28  56  49  49  42
29  14  21  15  33
30  59  10  32  89
31  52  28  46   9
32  98  71  80  89
33  82  81   8   7
34  53  64  89  23
35  88  18  83  67
36   7  57  81  94
37  89  95  72  80
38  55  55  78  87
39  74  70  83  89
40  78  65  14  36
41  16  97  46   2
42  17  23  35  81
43  25  18  69  21
44  27  63  56  20
45  94  54  84  67
46  41  65  39  79
47  55  33   6   4
48  10   7  40  27
49   6  88  77  15